name: firebase_auth_demo_flutter
description: Reference Authentication Flow with Flutter & Firebase

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.0.1+7

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  catcher: ^0.2.7
  flutter_swiper: ^1.1.6
  http: ^0.12.0+2
  connectivity: ^0.4.4
  url_launcher: ^4.0.2
  intl: ^0.15.7
  share: ^0.6.2+3
  datetime_picker_formfield: ^0.1.8
  random_string: 0.0.2
  firebase_auth: 0.14.0
  #o.14.0
  google_sign_in: 4.0.2

  provider: 3.0.0
  firebase_dynamic_links: 0.5.0
  rxdart: 0.22.1
  flutter_secure_storage: 3.2.1+1
  package_info: 0.4.0+6
  animated_text_kit: ^1.3.1
  flutter_datetime_picker: ^1.2.8
  #  firebase_cloud_messaging: ^4.0.4+1
  fluttertoast: ^3.1.3
  shared_preferences: ^0.5.4+3
  launch_review: ^2.0.0
  device_info: ^0.4.1+2
  rflutter_alert: ^1.0.3
  rate_my_app: ^0.4.0
  firebase_crashlytics: ^0.0.4+6




  #firebase_core: 0.4.0+8
  #firebase_messaging:
  #cloud_firestore: ^0.12.10

  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.2"
  font_awesome_flutter: ^8.2.0
  mockito: 4.0.0
  flutter_driver:
    sdk: flutter 
  test: any



flutter:


  uses-material-design: true


  assets:

    - assets/


    - assets/images/
    - assets/strokes/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/font/Montserrat-Regular.ttf

